%% Declare mexximp toolbox configuration.
%
% This script generates a JSON file which allows the Toolbox Toolbox to
% automatically install mexximp.
%
% 2016 benjamin.heasly@gmail.com

config = [ ...
    tbToolboxRecord( ...
    'name', 'exrtools', ...
    'type', 'docker', ...
    'url', 'ninjaben/exrtools-docker'), ...
    tbToolboxRecord( ...
    'name', 'mexximp_binary', ...
    'type', 'webget', ...
    'url', 'https://github.com/RenderToolbox3/mexximp/releases/download/v0.1.1/build.zip', ...
    'hook', 'clear mex'), ...
    tbToolboxRecord( ...
    'name', 'mexximp', ...
    'type', 'git', ...
    'url', 'https://github.com/RenderToolbox3/mexximp.git'), ...
    ];

pathHere = fileparts(mfilename('fullpath'));
configFile = fullfile(pathHere, 'mexximpToolboxConfig.json');
tbWriteConfig(config, 'configPath', configFile);
