classdef MexximpSceneTests < matlab.unittest.TestCase
    
    properties (Constant)
        emptyScene = struct( ...
            'cameras', [], ...
            'lights', [], ...
            'materials', [], ...
            'meshes', [], ...
            'embeddedTextures', [], ...
            'rootNode', []);
        floatTolerance = 1e-6;
        itemSize = 1:10;
    end
    
    methods (Test)
        
        function testEmptySceneRoundTrip(testCase)
            testCase.doSceneRoundTrip(testCase.emptyScene);
        end
        
        function testCamerasRoundTrip(testCase)
            scene = testCase.emptyScene;
            for s = testCase.itemSize
                scene.cameras = struct( ...
                    'name', MexximpSceneTests.randomString(s), ...
                    'position', rand(3, 1), ...
                    'lookAtDirection', rand(3, 1), ...
                    'upDirection', rand(3, 1), ...
                    'aspectRatio', num2cell(rand(1, s)), ...
                    'horizontalFov', num2cell(rand(1, s)), ...
                    'clipPlaneFar', num2cell(rand(1, s)), ...
                    'clipPlaneNear', num2cell(rand(1, s)));
                testCase.doSceneRoundTrip(scene);
            end
        end
        
        function testLightsRoundTrip(testCase)
            scene = testCase.emptyScene;
            for s = testCase.itemSize
                scene.lights = struct( ...
                    'name', MexximpSceneTests.randomString(s), ...
                    'position', rand(3, 1), ...
                    'type', MexximpSceneTests.randomLightTypes(s), ...
                    'lookAtDirection', rand(3, 1), ...
                    'innerConeAngle', num2cell(rand(1, s)), ...
                    'outerConeAngle', num2cell(rand(1, s)), ...
                    'constantAttenuation', num2cell(rand(1, s)), ...
                    'linearAttenuation', num2cell(rand(1, s)), ...
                    'quadraticAttenuation', num2cell(rand(1, s)), ...
                    'ambientColor', rand(3, 1), ...
                    'diffuseColor', rand(3, 1), ...
                    'specularColor', rand(3, 1));
                testCase.doSceneRoundTrip(scene);
            end
        end
        
    end
    
    methods (Access = private)
        function doSceneRoundTrip(testCase, scene)
            scenePrime = mexximpTest('scene', scene);
            testCase.assertEqual(scenePrime, scene, ...
                'AbsTol', testCase.floatTolerance);
        end
    end
    
    methods (Static)
        function string = randomString(stringSize)
            alphabet = '0':'z';
            string = alphabet(randi(numel(alphabet), [1, stringSize]));
        end
        
        function types = randomLightTypes(nTypes)
            allTypes = {'undefined', 'directional', 'point', 'spot'};
            types = allTypes(randi(numel(allTypes), [1, nTypes]));
        end
    end
end