classdef MexximpSceneTests < matlab.unittest.TestCase
    
    properties (Constant)
        emptyScene = struct( ...
            'cameras', [], ...
            'lights', [], ...
            'materials', [], ...
            'meshes', [], ...
            'embeddedTextures', [], ...
            'rootNode', []);
        floatTolerance = 1e-6;
        itemSize = 1:10;
    end
    
    methods (Test)
        
        function testEmptySceneRoundTrip(testCase)
            testCase.doSceneRoundTrip(testCase.emptyScene);
        end
        
        function testCamerasRoundTrip(testCase)
            scene = testCase.emptyScene;
            for size = testCase.itemSize
                scene.cameras = struct( ...
                    'name', [], ...
                    'position', [], ...
                    'lookAtDirection', [], ...
                    'upDirection', [], ...
                    'aspectRatio', num2cell(rand(1, size)), ...
                    'horizontalFov', num2cell(rand(1, size)), ...
                    'clipPlaneFar', num2cell(rand(1, size)), ...
                    'clipPlaneNear', num2cell(rand(1, size)));
                testCase.doSceneRoundTrip(scene);
            end
        end
    end
    
    methods (Access = private)
        function doSceneRoundTrip(testCase, scene)
            scenePrime = mexximpTest('scene', scene);
            testCase.assertEqual(scenePrime, scene, ...
                'AbsTol', testCase.floatTolerance);
        end
    end
end
