% Sandbox to try a bunch of previews of wild scenes.

clear;
clc;

hints.imageWidth = 640;
hints.imageHeight = 480;
commonArgs = { ...
    'hints', hints, ...
    'renderers', {'Mitsuba'}};

%% Millenium Falcon OBJ
%   http://tf3dm.com/3d-model/millenium-falcon-82947.html
%   Basically works fine
%   PBRT can't read the jpeg texture

scene = quickPreview('/home/ben/Downloads/4bw1cngyboxs_millenium_falcon/millenium-falcon.obj', ...
    commonArgs{:});
mexximpSceneScatter(scene);

%% Millenium Falcon 3DS
%   http://tf3dm.com/3d-model/millenium-falcon-82947.html
%   Geometry in here looks messed up:
%   "assimp info" and mexximpSceneBox() both show a huge bounding box.
%   mexximpSceneScatter() shows separate, distant clumps of vertices.

ignoreNodes = { ...
    'RADAR_AXL', ...
    'fr_geardr', ...
    'ff_geardr', ...
    'rl_gear', ...
    'rr_gear', ...
    'MT_FRONT', ...
    };
scene = quickPreview('/home/ben/Downloads/4bw1cngyboxs_millenium_falcon/millenium-falcon.3DS', ...
    commonArgs{:}, ...
    'ignoreNodes', ignoreNodes);
mexximpSceneScatter(scene, ...
    'ignoreNodes', ignoreNodes);

%% Bat Cave OBJ
%   http://www.turbosquid.com/3d-models/free-bat-cave-3d-model/639123
%   PBRT conversion is very slow -- 1400 meshes!
%       about 4 minutes for Mitsuba
%       10+ for our PBRT converter

% nodes named like "g Shape04" seem to be cruft.
nIgnore = 100;
ignoreNodes = cell(1, nIgnore);
for ii = 1:100
    ignoreNodes{ii} = sprintf('g Shape%02d', ii-1);
end

scene = quickPreview('/home/ben/Downloads/Batcave_MR_OBJ/batcave.obj', ...
    commonArgs{:}, ...
    'ignoreNodes', ignoreNodes, ...
    'viewExterior', false);
mexximpSceneScatter(scene, ...
    'ignoreNodes', ignoreNodes);

%% Bat Cave 3DS
%   http://www.turbosquid.com/3d-models/free-bat-cave-3d-model/639123
%   Looks reasonable in scatter, with light cruft around the edges.
%   Has 13 cameras, which is odd.
%   Had to create missing PIPE_TEX.JPG
%   Even with some ignore nodes, geometry looks messed up and spread out.

ignoreNodes = { ...
    'Cylinde100', ...
    'Cylinde102', ...
    'Cylinder98', ...
    'Cylinde104', ...
    'Cylinder74', ...
    'Cylinder96', ...
    'Plane07', ...
    'Cylinde103', ...
    'Cylinde101', ...
    'Cylinder99', ...
    'Cylinde105', ...
    'Cylinder04', ...
    'Cylinder74_inst_2', ...
    'Cylinde106_inst_10', ...
    'Cylinde172', ...
    };
scene = quickPreview('/home/ben/Downloads/Batcave_MR_3DS/batcave.3DS', ...
    commonArgs{:}, ...
    'ignoreNodes', ignoreNodes, ...
    'viewExterior', false);
mexximpSceneScatter(scene, ...
    'ignoreNodes', ignoreNodes);

%% Bat Cave Dae
%   http://www.turbosquid.com/3d-models/free-bat-cave-3d-model/639123
%   Had to create missing pipe_texture1.jpg
%   A bunch of cruft, includeing lights, camera, and meshes
%   Hard to remove the right cruft in order to center the camera.

ignoreNodes = { ...
    'Plane07', ...
    'Cylinder197', ...
    'Cylinder200', ...
    'Camera', ...
    'Sun01', ...
    'Sky02', ...
    'stage_light2', ...
    'mr_Sky_Portal02', ...
    'mr_Sky_Portal03', ...
    'window_1_light', ...
    'lantern', ...
    'window_2_light', ...
    'Cylinder249', ...
    'surface_rod9', ...
    'surface_rod8', ...
    'Cylinder107', ...
    'Cylinder105', ...
    'surface_pi', ...
    'Cylinder256', ...
    'Cylinder258', ...
    'Cylinder254', ...
    'Cylinder260', ...
    'Cylinder04', ...
    'Cylinder252', ...
    };
scene = quickPreview('/home/ben/Downloads/Batcave_MR_DAE/batcave.DAE', ...
    commonArgs{:}, ...
    'ignoreNodes', ignoreNodes, ...
    'viewAxis', [1 1 1], ...
    'viewExterior', false);
mexximpSceneScatter(scene, ...
    'ignoreNodes', ignoreNodes);

%% Night Club OBJ
%   http://www.turbosquid.com/3d-models/free-max-model-nightclub-4/711367
%   had to copy missing Stoneette6.png from the 3DS version
%   looks reasonable from the outside
%   looks reasonable from the inside

ignoreNodes = {};
scene = quickPreview('/home/ben/Downloads/stonetee OBJ/stonetee.obj', ...
    commonArgs{:}, ...
    'ignoreNodes', ignoreNodes, ...
    'viewExterior', false);
mexximpSceneScatter(scene, ...
    'ignoreNodes', ignoreNodes);

%% Night Club 3DS
%   http://www.turbosquid.com/3d-models/free-max-model-nightclub-4/711367
%   looks reasonable from the outside
%   looks reasonable from the inside
%   have to re-orient the view for 3DS

ignoreNodes = {};
scene = quickPreview('/home/ben/Downloads/Stonette 3DS/Club.3DS', ...
    commonArgs{:}, ...
    'ignoreNodes', ignoreNodes, ...
    'viewExterior', false, ...
    'viewAxis', [1 0 0], ...
    'viewUp', [0 0 1]);
mexximpSceneScatter(scene, ...
    'ignoreNodes', ignoreNodes);

%% Night Club FBX
%   http://www.turbosquid.com/3d-models/free-max-model-nightclub-4/711367
% Assimp says:
% FBX-DOM unsupported, old format version, supported are only FBX 2011, FBX 2012 and FBX 2013
